language: minimal

sudo: required

services:
  - docker
  
before_script:
  - echo "Build ownphotos ${DOCKER_TAG}"

env:
  global:
    - IMAGE_NAME=eloo/ownphotos
    - DOCKER_TAG=$IMAGE_NAME:$TRAVIS_BRANCH
    - DOCKER_COMPOSE_VERSION=1.25.5

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

stages:
  - build
  - test
  - deploy

cache:
  directories:
    - /var/lib/docker/

jobs:
  include:
    - stage: build
      script: 
        - make build
        - docker-compose -f docker-compose.travis.yml up -d
        - curl localhost:3000
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker push "${DOCKER_TAG}"
    - stage: test
      # script:
      #   - docker-compose -f docker-compose.travis.yml up -d
      #   - curl localhost:3000
    # - stage: deploy
    #   if: branch in (dev,master)
    #   script:
    #     - docker push "${DOCKER_TAG}"
