sudo: required

services:
  - docker

before_script:
  - echo "Build ownphotos"

env:
  global:
    - IMAGE_NAME=eloo/ownphotos 
    - DOCKER_TAG=$IMAGE_NAME:$TRAVIS_BRANCH
    - DOCKER_COMPOSE_VERSION=1.25.5

before_install:
  script:
    - curl google.de


stages:
  - build
  - test
  - deploy

jobs:
  include:
    - stage: build
      script: 
        - make build
    - stage: test
      script:
        - docker-compose -f docker-compose.travis.yml up
        - curl localhost:3000
    - stage: deploy
      if: branch in (dev,master)
      script:
        - docker push "${DOCKER_TAG}"
